apiVersion: batch/v1
kind: CronJob
metadata:
  name: balances-ap
  namespace: ap
spec:
  schedule: "5 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: balances-ap
              image: gandralf/balances_ap:latest
              imagePullPolicy: Always
              env:
                - name: SFTP_HOST
                  value: "209.159.147.64"
                - name: SFTP_USERNAME
                  value: brxbrasil
                - name: SFTP_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ap-secrets
                      key: FTP_PASSWORD 
                - name: IGNORE_ACCOUNTS
                  value: "1,2,3,1252,1253,1834,12266,35395,46037,49855,315441,370117"
                - name: RABBITMQ_URL
                  valueFrom:
                    secretKeyRef:
                      name: fireblocks-secrets
                      key: RABBITMQ_URL
                - name: SENTRY_DSN
                  value: "https://466d62901245948af6741ad8ec624e01@o142813.ingest.us.sentry.io/4508994421653504"
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: dockerhub-secret
